#!/bin/sh
if [ -z "$BLACKLIST_MODE" ]; then
  BLACKLIST_MODE=0
fi


if [ -z "$QUERY_LOG_TO_STDOUT" ]; then
  DEBUG_QUERY=0
fi

SEARCHD_NLP=""
NLP_CONF=/etc/manticoresearch/conf_mount/searchd_include.conf
if [ -f "$NLP_CONF" ]; then
    SEARCHD_NLP=$(cat $NLP_CONF)
fi


ip=`hostname -i`
cat << EOF

common
{
    plugin_dir = /etc/manticoresearch/plugins/
    lemmatizer_base = /usr/share/manticore/
}


searchd {
	listen = /var/run/mysqld/mysqld.sock:mysql41
    listen = 9306:mysql41
    listen = 9301:mysql_vip
    listen = 9308:http
    listen = $ip:9312
    listen = $ip:9315-9325:replication
    network_timeout = 5
    seamless_rotate = 1
    preopen_tables = 1
    unlink_old = 1
    rt_flush_period = 60
    max_packet_size = 128M
    mysql_version_string = 5.5.21
#    log = /var/lib/manticore/searchd.log
#    query_log = /dev/stdout
#    query_log_format = sphinxql
    pid_file = /var/run/manticore/searchd.pid
    data_dir = /var/lib/manticore
    not_terms_only_allowed = $BLACKLIST_MODE
    query_log_commands = $QUERY_LOG_TO_STDOUT
    $(echo "$SEARCHD_NLP")
}
EOF
