<?php

namespace Tests\Cluster;

use App\Models\Destination;
use App\Models\Processes;
use App\Models\Source;
use App\Services\ManticoreService;
use Tests\TestCase;
use Tests\Traits\AuthTrait;


/**
 * @group application
 */
class ClusterTest extends TestCase
{
    use AuthTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \Session::start();
    }

    /**
     * @test
     */
    public function createSource(): void
    {
        $data = [
            'name'  => "source",
            'host'  => 'my-kafka-controller-0.my-kafka-controller-headless.kafka.svc.cluster.local:9092',
            'topic' => 'my-docs',
            'group' => 'ms_test_stream',
            '_token' => csrf_token()
        ];

        $response = $this->actingAs($this->getAdmin())->post("/admin/source/add", $data);
        $response->assertStatus(200);

        $newGoals = Source::where(['name' => $data['name']])->first();

        $this->assertSame([$newGoals->name, $newGoals->host, $newGoals->topic, $newGoals->group],
            [$data['name'], $data['host'], $data['topic'], $data['group']]);

        $response->assertExactJson([
            "success" => "Record is successfully added",
            "id"      => $newGoals->id,
        ]);
    }


    /**
     * @test
     */
    public function createDestination(): void
    {
        $data = [
            'name'  => "destination",
            'host'  => 'my-kafka-controller-0.my-kafka-controller-headless.kafka.svc.cluster.local:9092',
            'topic' => 'my-results',
            '_token' => csrf_token()
        ];

        $response = $this->actingAs($this->getAdmin())->post("/admin/destination/add", $data);
        $response->assertStatus(200);

        $newGoals = Destination::where(['name' => $data['name']])->first();

        $this->assertSame([$newGoals->name, $newGoals->host, $newGoals->topic],
            [$data['name'], $data['host'], $data['topic']]);

        $response->assertExactJson([
            "success" => "Record is successfully added",
            "id"      => $newGoals->id,
        ]);
    }

    /**
     * @test
     */

    public function createProcessing()
    {
        $destination = Destination::first();
        $source      = Source::first();

        self::assertNotEmpty($source);
        self::assertNotEmpty($destination);

        /**
         *
         * export LABEL="m1"
         * OUTPUT_DOCS="0011"
         * TRANSFORM_RULES="whole_document => json|text.status.retweeted_status.user.url&&text.comment.status.user.url&&text.comment.status.retweeted_status.user.url&&text.comment.reply_comment.user.url&&text.comment.reply_comment.text&&text.comment.status.statusurl&&text.status.statusurl&&text.comment.user.url&&text.comment.reply_comment.status.user.url&&text.comment.source => url|text.comment.status.source => source|text.comment.status.text => text|text.comment.text => title|text.status.text => statustext"
         * MANTICORE_FIELDS="json=json|url=url|text=source|text=text|text=title|text=statustext"
         * LOG_LEVEL="WARN"
         * SUSPEND="0"
         * SCALER_HOST="localhost:8808"
         * KAFKA_INPUT_HOST="localhost:29092"
         * KAFKA_OUTPUT_HOST="localhost:29092"
         * MANTICORE_HOST="localhost:9306"
         * KAFKA_INPUT_TOPIC="my-docs"
         * KAFKA_OUTPUT_TOPIC="my-results"
         * KAFKA_GROUP_NAME="streams-manticore"
         * MIN_THREADS="1"
         * MAX_THREADS="1"
         * PROCESSED_MEASURE_TIME="60"
         * METRICS_STORAGE_TTL="31"
         * MAX_BATCH_SIZE="5000"
         * METRICS_STORAGE_URL="localhost:8123"
         * DEBUG_PROCESSING=1
         *
         */

        $response = $this->actingAs($this->getAdmin())->postJson('/admin/process/add',
            [
                'name'                        => "processing",
                'source_id'                   => $source->id,
                'destination_id'              => $destination->id,
                'language'                    => 'chinese',
                'query_complexity_validation' => 0,
                'max_batch_size'              => 5000,
                'min_threads'                 => 1,
                'max_threads'                 => 1,
                 'searchd_settings'            => '',
                'attrs'                       => '[{"name":"json","path":"whole_document","type":"json"},{"name":"source","path":"text.comment.status.source","type":"string"},{"name":"text","path":"text.comment.status.text","type":"string"},{"name":"title","path":"text.comment.text","type":"string"},{"name":"statustext","path":"text.status.text","type":"string"},{"name":"url","path":"text.status.retweeted_status.user.url&&text.comment.status.user.url&&text.comment.status.retweeted_status.user.url&&text.comment.reply_comment.user.url&&text.comment.reply_comment.text&&text.comment.status.statusurl&&text.status.statusurl&&text.comment.user.url&&text.comment.reply_comment.status.user.url&&text.comment.source","type":"url"}]',
                'output_docs'                 => '0010',
                '_token' => csrf_token()
            ]);

        $response->assertStatus(200);
        $response->assertJsonFragment(['status' => 'success']);
    }

    /**
     * @test
     */
     public function assignUser(): void
     {
         $process = Processes::first();
         self::assertNotNull($process);
         $manager = $this->getManager();


        $response = $this->actingAs($this->getAdmin())->post('/admin/process/assignUser',
            ['process_id' => $process->id, 'assign_user' => $manager->id,
             '_token' => csrf_token()]);

        $response->assertStatus(200);
        $manager->refresh();
        $process->refresh();
        $streams = $process->streams->pluck('id')->toArray();
        $this->assertTrue(in_array($manager->process, $streams));
    }

    /**
     * @test
     */
    public function deployWait()
    {
        $manager = $this->getManager();
        \Auth::setUser($manager);
        /** @var ManticoreService $manticoreService */
        $manticoreService = app(ManticoreService::class);
        for ($i = 1; $i <= 20; $i++) {
            $manticoreService->setStream($manager->process);
            $error = $manticoreService->getError();
            if($error === ''){
                break;
            }

            echo $error."\n";
            sleep(5);
        }

        self::assertSame($error, '');
    }

    /**
     * @test
     */
    public function addRules()
    {
        $manager = $this->getManager();
        \Auth::setUser($manager);
        /** @var ManticoreService $manticoreService */
        $manticoreService = app(ManticoreService::class);
        $manticoreService->setStream($manager->process);
        $manticoreService->truncateRules();

        $rules = ['经', '小', '集', '喜', '@url http://www.xiaomi.com',
                  '@url http://blog.sina.com.cn/liyunjie999',
                  '@url http://blog.sina.com.cn/cosmopolitan2008'];

        foreach ($rules as $rule){
            $response = $this->actingAs($manager)->post('/manager/addRule', ['rule_text' => $rule, '_token' => csrf_token()]);
            $response->assertStatus(200);
        }
    }
}
