{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "manticore-streams.fullname" . }}
  labels:
    name: {{ include "manticore-streams.name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    {{- include "manticore-streams.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.podSecurityPolicy.annotations }}
  {{ toYaml .Values.podSecurityPolicy.annotations | indent 4 }}
  {{- end }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  volumes:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  {{- end }}
