<?php


return [
    'russian' => ['morphology' => 'lemmatize_ru', 'charset_table' => ['non_cjk'], 'stopwords' => 'ru'],
    'english' => ['morphology' => 'lemmatize_en', 'charset_table' => ['non_cjk'], 'stopwords' => 'en'],
    'deuch' => ['morphology' => 'lemmatize_de', 'charset_table' => ['non_cjk'], 'stopwords' => 'de'],
    'russian_all' => ['morphology' => 'lemmatize_ru_all', 'charset_table' => ['non_cjk'], 'stopwords' => 'ru'],
    'english_all' => ['morphology' => 'lemmatize_en_all', 'charset_table' => ['non_cjk'], 'stopwords' => 'en'],
    'deuch_all' => ['morphology' => 'lemmatize_de_all', 'charset_table' => ['non_cjk'], 'stopwords' => 'de'],
    'english/russian' => ['morphology' => 'stem_enru', 'charset_table' => ['non_cjk'], 'stopwords' => 'en, ru'],
    'arabic' => ['morphology' => 'stem_ar', 'charset_table' => ['non_cjk'], 'stopwords' => 'ar'],
    'basque' => ['morphology' => 'stem_baq', 'charset_table' => ['non_cjk'], 'stopwords' => 'eu'],
    'catalan' => ['morphology' => 'stem_ca', 'charset_table' => ['non_cjk'], 'stopwords' => 'ca'],
    'сzech' => ['morphology' => 'stem_cz', 'charset_table' => ['non_cjk'], 'stopwords' => 'cz'],
    'danish' => ['morphology' => 'stem_da', 'charset_table' => ['non_cjk'], 'stopwords' => 'da'],
    'dutch' => ['morphology' => 'stem_nl', 'charset_table' => ['non_cjk'], 'stopwords' => 'nl'],
    'finnish' => ['morphology' => 'stem_fi', 'charset_table' => ['non_cjk'], 'stopwords' => 'fi'],
    'french' => ['morphology' => 'stem_fr', 'charset_table' => ['non_cjk'], 'stopwords' => 'fr'],
    'greek' => ['morphology' => 'stem_el', 'charset_table' => ['non_cjk'], 'stopwords' => 'el'],
    'hindi' => ['morphology' => 'stem_hi', 'charset_table' => ['non_cjk'], 'stopwords' => 'hi'],
    'hungarian' => ['morphology' => 'stem_hu', 'charset_table' => ['non_cjk'], 'stopwords' => 'hu'],
    'irish' => ['morphology' => 'stem_ga', 'charset_table' => ['non_cjk'], 'stopwords' => 'ga'],
    'italian' => ['morphology' => 'stem_it', 'charset_table' => ['non_cjk'], 'stopwords' => 'it'],
    'lithuanian' => ['morphology' => 'stem_lt', 'charset_table' => ['non_cjk'], 'stopwords' => 'lt'],
    'norwegian' => ['morphology' => 'stem_no', 'charset_table' => ['non_cjk'], 'stopwords' => 'no'],
    'portuguese' => ['morphology' => 'stem_pt', 'charset_table' => ['non_cjk'], 'stopwords' => 'pt'],
    'romanian' => ['morphology' => 'stem_ro', 'charset_table' => ['non_cjk'], 'stopwords' => 'ro'],
    'spanish' => ['morphology' => 'stem_es', 'charset_table' => ['non_cjk'], 'stopwords' => 'es'],
    'swedish' => ['morphology' => 'stem_sv', 'charset_table' => ['non_cjk'], 'stopwords' => 'sv'],
    'turkish' => ['morphology' => 'stem_tr', 'charset_table' => ['non_cjk'], 'stopwords' => 'tr'],
    'chinese' => ['morphology' => 'icu_chinese', 'charset_table' => ['cjk', 'non_cjk'], 'stopwords' => 'zh'],
    'nepali' => ['morphology' => 'stem_ne', 'charset_table' => ['non_cjk']],
    'soundex' => ['morphology' => 'soundex', 'charset_table' => ['non_cjk', 'cjk']],
    'tamil' => ['morphology' => 'stem_ta', 'charset_table' => ['non_cjk']],
    'metaphone' => ['morphology' => 'metaphone', 'charset_table' => ['non_cjk', 'cjk']],
    'custom' => ['morphology' => '', 'charset_table' => ['']],
];
