pid        /tmp/nginx.pid;
events {
}
http {
    include    mime.types;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
    default_type application/octet-stream;
    log_format custom '$remote_addr [$time_local] $request_time $request $status';

    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        client_body_buffer_size     50M;
        client_max_body_size        50M;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_cache off;
        root /var/www/html/public;
        access_log /dev/stdout custom;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        charset utf-8;
        index index.php;
        server_name _;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ ^/(status|ping)$ {
            include fastcgi_params;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass ui:9000;
            fastcgi_index index.php;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass ui:9000;
        }
    }
}
